version: "3"

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/home/riker/workspace
      - ~/.gitconfig:/home/riker/.gitconfig
      - ~/.ssh:/home/riker/.ssh

    command: sleep infinity